#include "ru.h"
#include <unordered_map>

// ============================ Испанский ============================
// Отдельный файл на язык: добавление следующего не требует правок ни здесь,
// ни в ru.cpp. Ключа может не быть - tr() тогда покажет английский.
//
// Терминология подобрана по тому, как говорят в криптосообществе Латинской
// Америки и Испании: "wallet" переведено как "billetera" (нейтрально для обоих
// регионов), а заимствования, ставшие стандартом - trader, long, short, PnL -
// оставлены как есть. Переводить их значило бы усложнить чтение тем, кто
// каждый день видит их по-английски на биржах.

namespace {

const std::unordered_map<std::string, const char*>& tableEs() {
    static const std::unordered_map<std::string, const char*> t = {
        // --- Типы операций в алертах ---
        {"alert_buy", "COMPRA"},
        {"alert_sell", "VENTA"},
        {"alert_transfer", "TRANSFERENCIA"},
        {"alert_add_liquidity", "APORTE DE LIQUIDEZ"},
        {"alert_remove_liquidity", "RETIRO DE LIQUIDEZ"},
        {"alert_collect_fees", "COBRO DE COMISIONES"},
        {"alert_wrap", "WRAP"},
        {"alert_unwrap", "UNWRAP"},
        {"alert_bridge_out", "SALIDA POR PUENTE"},
        {"alert_bridge_in", "ENTRADA POR PUENTE"},
        {"alert_arbitrage", "ARBITRAJE"},
        {"alert_amount", "Importe"},
        {"alert_token", "Token"},
        {"alert_qty", "Cantidad"},
        {"alert_buy_price", "Precio de compra"},
        {"alert_sell_price", "Precio de venta"},
        {"alert_gas", "Comisión de red"},
        {"alert_spent", "Gastado"},
        {"alert_received", "Recibido"},
        {"alert_contract", "Contrato"},
        {"alert_wallet", "Billetera"},
        {"alert_transaction", "Transacción"},

        // --- Главное меню ---
        {"menu_title", "🚨 <b>Wallet Tracker</b>"},
        {"menu_add_wallet", "➕ Añadir billetera"},
        {"menu_my_wallets", "💼 Mis billeteras"},
        {"menu_alert_threshold", "💰 Umbral de alertas"},
        {"menu_account", "👤 Mi cuenta"},
        {"account_title", "👤 <b>Mi cuenta</b>"},
        {"account_desc", "Tus billeteras seguidas y lo que tienen ahora mismo."},
        {"menu_hold", "💎 Cartera"},
        {"hold_title", "💎 <b>Cartera</b>"},
        {"hold_choose", "Elige una billetera para ver lo que tiene ahora mismo:"},
        {"hold_loading", "⏳ Leyendo saldos desde la blockchain, esto tarda unos segundos..."},
        {"hold_total", "Valor total"},
        {"hold_coins", "Monedas en cartera"},
        {"hold_empty", "No se encontraron monedas por $10 o más en esta billetera."},
        {"hold_illiquid", "Las posiciones marcadas superan el tamaño de su pool: el precio de mercado mostrado no es alcanzable al vender."},
        {"hold_partial", "⚠️ Algunos saldos no se pudieron leer ahora mismo, el total puede estar incompleto."},
        {"hold_dust_note", "Las posiciones por debajo de $10 no se muestran."},
        {"hold_no_history", "Todavía no hemos visto operar a esta billetera, así que no hay nada que comprobar salvo el saldo nativo."},
        {"menu_top_traders", "🏆 Mejores traders"},
        {"menu_premium", "⭐ Premium"},
        {"menu_languages", "🌐 Idioma"},
        {"menu_help", "❓ Ayuda"},
        {"menu_no_wallets", "Todavía no sigues ninguna billetera.\nPulsa <b>Añadir billetera</b> para empezar a recibir alertas."},
        {"menu_tracking_prefix", "Siguiendo"},
        {"menu_alerts_above", "alertas desde"},
        {"back_button", "← Atrás"},
        {"cancel_button", "❌ Cancelar"},

        // --- Añadir billetera ---
        {"add_wallet_title", "➕ <b>Añadir billetera</b>\n\nEnvía la dirección de la billetera que quieres seguir — formato 0x..., 42 caracteres.\n\n💡 <b>¿No sabes qué billetera añadir?</b>\nLa pestaña 🏆 <b>Mejores traders</b> ordena las billeteras más rentables de los últimos 30 días: elige cualquiera y empieza a seguirla con un toque.\nO pega una dirección desde un explorador de bloques o un servicio de análisis."},
        {"add_wallet_addr_ok", "✅ Dirección aceptada.\n\nAhora escribe un nombre para esta billetera — hasta 32 caracteres (por ejemplo, \"Binance\"):"},
        {"add_wallet_invalid", "❌ Dirección de billetera no válida.\n\nLa dirección debe empezar por 0x y tener 42 caracteres. Escribe una dirección válida o pulsa Cancelar."},
        {"add_wallet_success", "✅ <b>Billetera añadida</b>"},
        {"add_wallet_name_label", "Nombre:"},
        {"add_wallet_address_label", "Dirección:"},
        {"add_wallet_tracking_enabled", "Seguimiento activado."},
        {"track_name_prompt", "🏷 Escribe un nombre para este trader:"},
        {"token_search_prompt", "🪙 <b>Mejor PnL por token</b>\n\nEscribe el símbolo de un token (por ejemplo <code>CAKE</code>) o una dirección de contrato (<code>0x...</code>):"},
        {"token_search_empty", "❌ Escribe el símbolo de un token o una dirección de contrato, o pulsa Cancelar."},
        {"remove_confirm_title", "🗑️ <b>¿Eliminar billetera?</b>"},
        {"remove_confirm_notice", "Dejarás de recibir alertas de esta billetera."},
        {"remove_yes", "🗑️ Sí, eliminar"},
        {"toast_wallet_removed", "✅ Billetera eliminada"},

        // --- Umbral de alertas ---
        {"err_invalid_number", "❌ Número no válido."},
        {"err_threshold_positive", "❌ El umbral debe ser positivo."},
        {"err_threshold_too_small", "❌ El umbral mínimo de alerta es $50. Introduce $50 o más."},
        {"err_threshold_too_large", "❌ El umbral es demasiado alto."},
        {"err_threshold_decimals", "❌ Usa como máximo 2 decimales (por ejemplo, 7500.50)."},
        {"threshold_retry_hint", "\n\nIntroduce un importe válido (por ejemplo, 7500 o 7500.50) o pulsa Cancelar."},
        {"threshold_unchanged", "ℹ️ El umbral actual ya es"},
        {"threshold_updated", "✅ <b>Umbral de alertas actualizado</b>\n\nUmbral actual:"},
        {"threshold_save_failed", "❌ No se pudo guardar el umbral. Inténtalo de nuevo."},
        {"threshold_title", "💰 <b>Umbral de alertas</b>"},
        {"threshold_desc", "Solo recibirás alertas de transacciones iguales o superiores a este importe."},
        {"threshold_current", "Umbral actual:"},
        {"threshold_choose", "Elige un valor predefinido o introduce un importe personalizado:"},
        {"threshold_custom_btn", "✏️ Importe personalizado"},
        {"threshold_custom_title", "💰 <b>Umbral personalizado</b>\n\nIntroduce el importe mínimo de alerta en USD — desde $50 en adelante (por ejemplo, 7500 o 7500.50):"},
        {"unknown_command", "🤔 Usa el menú de abajo."},

        // --- Idioma ---
        {"lang_title", "🌐 <b>Idioma</b>"},
        {"lang_current", "Idioma actual:"},
        {"lang_choose", "Elige el idioma de las alertas y los menús:"},

        // --- Mis billeteras ---
        {"rk_generating", "⏳ El ranking se está generando.\n\nInténtalo de nuevo en un minuto."},
        {"mw_no_wallets", "Todavía no sigues ninguna billetera."},
        {"mw_tap_add", "Pulsa ➕ <b>Añadir billetera</b> para empezar a seguirla."},
        {"mw_free_notice1", "ℹ️ Plan gratuito: las alertas solo están activas para tu primera billetera (🔔)."},
        {"mw_free_notice2", "El resto de tus billeteras están guardadas (⏸) y se reactivarán con Premium."},
        {"mw_upgrade", "⭐ Pasar a Premium"},
        {"ws_title", "📊 <b>Estadísticas de la billetera</b>"},
        {"ws_rank", "Puesto"},
        {"ws_not_in_ranking", "(fuera del ranking de 30D)"},
        {"ws_winrate", "Aciertos"},
        {"ws_trades_30d", "Operaciones (30D)"},
        {"ws_last_trade", "Última operación"},

        // --- Rankings ---
        {"rk_top_pnl_30d", "Mejor PnL (30D)"},
        {"rk_top_traders_30d", "Mejores traders (30D)"},
        {"rk_top_roi_30d", "Mejor ROI (30D)"},
        {"rk_roi_per_trade", "ROI por operación"},
        {"rk_top_winrate_30d", "Mejor tasa de aciertos (30D)"},
        {"rk_most_active_30d", "Más activos (30D)"},
        {"rk_smart_contract", "Contrato inteligente"},
        {"rk_no_wallets_min_trades1", "No hay billeteras con al menos"},
        {"rk_no_wallets_min_trades2", "operaciones cerradas en los últimos 30 días."},
        {"rk_no_completed_trades", "Todavía no hay operaciones cerradas en los últimos 30 días."},
        {"rk_prev", "⬅️ Anterior"},
        {"rk_next", "Siguiente ➡️"},
        {"rk_track", "➕ Seguir"},
        {"rk_avg_hold", "Tiempo medio"},
        {"unit_day", "d"},
        {"unit_hour", "h"},
        {"unit_min", "min"},
        {"unit_sec", "s"},
        {"rk_trades", "Operaciones"},
        {"rk_unlock_top100", "🔒 Desbloquea el Top 100 con Premium."},
        {"rk_choose_ranking", "Elige un ranking:"},
        {"rk_btn_top_pnl", "💵 Mejor PnL"},
        {"rk_btn_top_roi", "📈 Mejor ROI"},
        {"rk_btn_top_winrate", "🎯 Mejor tasa de aciertos"},
        {"rk_btn_most_active", "🔄 Más activos"},
        {"rk_btn_top_pnl_by_token", "🪙 Mejor PnL por token"},
        {"rk_unknown_token1", "❌ Token desconocido:"},
        {"rk_unknown_token2", "Indica la dirección del contrato directamente, o un símbolo que el bot ya haya visto en alguna operación."},
        {"rk_expired", "⏳ Este ranking ha caducado. Busca el token de nuevo desde el menú."},

        // --- Ayuda ---
        {"help_title", "❓ <b>Ayuda</b>"},
        {"help_intro", "🏆 Descubre a los mejores traders on-chain, sigue billeteras y recibe alertas de operaciones en tiempo real en las redes admitidas."},
        {"help_commands", "<b>Usa los botones del menú para:</b>"},
        {"help_menu_add", "➕ Añadir billetera — seguir una billetera nueva"},
        {"help_menu_mywallets", "💼 Mis billeteras — ver y gestionar las billeteras que sigues"},
        {"help_menu_threshold", "💰 Umbral de alertas — fijar el importe mínimo de alerta"},
        {"help_menu_top", "🏆 Mejores traders — ver el ranking de billeteras por resultados"},
        {"help_menu_premium", "⭐ Premium — ver los planes Premium"},
        {"help_menu_languages", "🌐 Idioma — cambiar de idioma"},
        {"help_premium_title", "⭐ <b>Premium</b>"},
        {"help_premium_1", "• Acceso completo al Top 100 de traders"},
        {"help_premium_2", "• Seguimiento de hasta 50 billeteras"},
        {"help_premium_3", "• Funciones avanzadas"},
        {"help_premium_4", "• Acceso prioritario a las novedades"},
        {"help_disclaimer", "⚠️ <b>Aviso legal</b>\nEl bot muestra transacciones on-chain que ya han ocurrido. Es un servicio de información, no asesoramiento financiero ni una recomendación de inversión. Los resultados pasados de una billetera no predicen los futuros. Operar con apalancamiento puede costarte todo tu depósito. Las decisiones las tomas tú y el riesgo lo asumes tú."},
        {"help_support", "📞 Soporte: @WalletTrackerHelp"},
        {"help_channel", "📢 Canal: t.me/WalletTrackerOfficial"},
        {"help_footer", "Usa el menú principal para acceder rápido a todas las funciones."},

        // --- Premium ---
        {"pr_active_title", "⭐ <b>Premium activo</b>"},
        {"pr_service_account", "Cuenta de servicio — el acceso Premium es permanente."},
        {"pr_valid_until_inline", "Tu suscripción es válida hasta"},
        {"pr_days_left", "días restantes:"},
        {"pr_active_benefits", "Tienes acceso al seguimiento de hasta 50 billeteras y al Top 100 de traders completo."},
        {"pr_renew", "🔄 Renovar Premium"},
        {"pr_title", "⭐ <b>Wallet Tracker Premium</b>"},
        {"pr_unlock", "Aprovecha todo el potencial de Wallet Tracker."},
        {"pr_includes", "<b>Premium incluye:</b>"},
        {"pr_50_wallets", "✅ Seguimiento de hasta 50 billeteras en lugar de 1 del plan gratuito"},
        {"pr_top100", "✅ Acceso al Top 100 de traders completo (el Top 30 es gratuito)"},
        {"pr_subscription_label", "<b>Suscripción:</b> 30 días"},
        {"pr_price_label", "<b>Precio:</b>"},
        {"pr_buy", "⭐ Comprar Premium"},
        {"pr_limit_title", "⚠️ <b>Límite de billeteras alcanzado</b>"},
        {"pr_limit_free", "El plan gratuito permite seguir solo 1 billetera."},
        {"pr_limit_upgrade", "Pasa a Premium para seguir hasta 50 billeteras."},
        {"invoice_title", "Wallet Tracker Premium"},
        {"invoice_description", "Suscripción Premium de 30 días"},
        {"invoice_price_label", "Premium (30 días)"},
        {"invoice_unknown_product", "Producto desconocido. Inténtalo de nuevo."},
        {"payments_unavailable", "Los pagos no están disponibles temporalmente. Inténtalo más tarde."},
        {"payment_success_title", "✅ ¡Pago realizado!"},
        {"payment_success_activated", "Wallet Tracker Premium se ha activado."},
        {"payment_success_duration", "Válido durante 30 días."},

        // --- Límites y errores ---
        {"limit_50_reached", "⚠️ Has alcanzado el límite de 50 billeteras seguidas."},
        {"already_tracking", "⚠️ Ya estás siguiendo esta billetera."},
        {"toast_already_tracking", "✅ Ya la sigues"},
        {"wallet_limit_50_short", "⚠️ Límite de billeteras alcanzado (50)"},
        {"free_plan_1_wallet", "⚠️ El plan gratuito permite seguir solo 1 billetera. Pasa a Premium — pulsa ⭐ Premium en el menú."},
        {"already_tracking_retry", "⚠️ Ya estás siguiendo esta billetera.\n\nIntroduce otra dirección o pulsa Cancelar."},
        {"wallet_bot_banned", "🤖 Esta billetera fue marcada como bot y excluida del ranking de forma permanente. La cuenta de servicio no puede seguirla.\n\nIntroduce otra dirección o pulsa Cancelar."},
        {"toast_invalid_address", "❌ Dirección no válida."},
        {"track_now_tracked", "✅ La billetera"},
        {"track_now_tracked_suffix", "ya se está siguiendo."},
        {"generic_error_retry", "❌ Algo ha fallado, inténtalo de nuevo."},
        {"err_invalid_address", "❌ Dirección de billetera no válida."},
        {"err_loading_wallet", "❌ Error al cargar la billetera."},
        {"err_loading_wallets", "❌ Error al cargar las billeteras."},
        {"op_cancelled", "❌ Operación cancelada."},
        {"err_invoice_failed", "❌ No se pudo crear la factura. Inténtalo más tarde."},
        {"err_user_limit", "⚠️ Límite de usuarios alcanzado. Inténtalo más tarde."},
        {"err_wallet_not_found", "❌ La billetera no está en tu lista."},
        {"rename_title", "✏️ <b>Renombrar billetera</b>"},
        {"rename_current_name", "Nombre actual:"},
        {"rename_enter_new", "Introduce un nombre nuevo:"},
        {"rename_success", "✅ <b>Billetera renombrada</b>"},
        {"rename_new_name", "Nombre nuevo:"},
        {"err_name_empty", "❌ El nombre no puede estar vacío.\n\nIntroduce un nombre o pulsa Cancelar."},
        {"err_name_too_long", "❌ El nombre es demasiado largo (máx. 32 caracteres).\n\nIntroduce un nombre más corto o pulsa Cancelar."},

        // --- Futuros perpetuos de Hyperliquid ---
        {"hl_open_long", "ABRIÓ LARGO"},
        {"hl_close_long", "CERRÓ LARGO"},
        {"hl_open_short", "ABRIÓ CORTO"},
        {"hl_close_short", "CERRÓ CORTO"},
        {"hl_flip", "DIO LA VUELTA"},
        {"hl_liquidated", "LIQUIDADO"},
        {"hl_trade", "OPERACIÓN PERP"},
        {"hl_trade_size", "Tamaño de la operación"},
        {"hl_position_size", "Tamaño de la posición"},
        {"hl_collateral", "Garantía"},
        {"hl_of_account", "de la cuenta"},
        {"hl_position_closed", "Posición cerrada por completo"},
        {"hl_fills_in_series", "Operaciones en esta serie"},
        {"hl_leverage", "Apalancamiento"},
        {"hl_cross", "cruzado"},
        {"hl_isolated", "aislado"},
        {"hl_price", "Precio"},
        {"hl_qty", "Cantidad"},
        {"hl_pnl", "PnL realizado"},
        {"hl_liq", "Liquidación"},
        {"hl_account", "Valor de la cuenta"},
        {"hl_venue", "Plataforma"},
        {"hl_venue_title", "Mejores traders"},
        {"hl_venue_choose", "Elige la plataforma:\n<i>Spot en BSC o futuros perpetuos en Hyperliquid</i>"},
        {"hl_venue_spot", "🟡 BSC — Spot"},
        {"hl_venue_perp", "🔵 Hyperliquid — Futuros"},
        {"hl_rk_title", "mejores traders, 30 días"},
        {"hl_rk_choose", "Elige un ranking:"},
        {"hl_locked_body", "Los futuros perpetuos están disponibles con Premium.\n\nObtienes el apalancamiento, la garantía y el precio de liquidación de cada operación, el PnL realizado directamente de la bolsa y el ranking de traders de 30 días."},
        {"hl_rk_leverage", "Apalancamiento medio"},
        {"hl_rk_roi_account", "ROI sobre el depósito"},
        {"hl_rk_empty", "Todavía no hay datos: el ranking necesita al menos 5 operaciones cerradas por billetera en 30 días."},
    };
    return t;
}

} // namespace

const char* trEs(const std::string& key) {
    const auto& t = tableEs();
    auto it = t.find(key);
    return it == t.end() ? nullptr : it->second;
}
