#include "ru.h"
#include <unordered_map>

// ========================= Português (Brasil) =========================
// Отдельный файл на язык - см. lang_es.cpp. Ключа может не быть: tr() тогда
// покажет английский, а не пустоту.
//
// Вариант бразильский, а не европейский: Бразилия - крупнейший рынок Telegram
// среди португалоязычных и один из крупнейших крипто-рынков мира. Различия
// заметны в бытовой лексике ("carteira" против "carteira", но "usuário"
// против "utilizador"), и выбирать надо тот, где аудитория.
//
// Устоявшиеся заимствования - trader, long, short, PnL, spot, wrap - оставлены
// как есть: на биржах они каждый день видны по-английски.

namespace {

const std::unordered_map<std::string, const char*>& tablePt() {
    static const std::unordered_map<std::string, const char*> t = {
        // --- Tipos de operação nos alertas ---
        {"alert_buy", "COMPRA"},
        {"alert_sell", "VENDA"},
        {"alert_transfer", "TRANSFERÊNCIA"},
        {"alert_add_liquidity", "ADIÇÃO DE LIQUIDEZ"},
        {"alert_remove_liquidity", "REMOÇÃO DE LIQUIDEZ"},
        {"alert_collect_fees", "COLETA DE TAXAS"},
        {"alert_wrap", "WRAP"},
        {"alert_unwrap", "UNWRAP"},
        {"alert_bridge_out", "SAÍDA POR PONTE"},
        {"alert_bridge_in", "ENTRADA POR PONTE"},
        {"alert_arbitrage", "ARBITRAGEM"},
        {"alert_amount", "Valor"},
        {"alert_token", "Token"},
        {"alert_qty", "Quantidade"},
        {"alert_buy_price", "Preço de compra"},
        {"alert_sell_price", "Preço de venda"},
        {"alert_gas", "Taxa de rede"},
        {"alert_spent", "Gasto"},
        {"alert_received", "Recebido"},
        {"alert_contract", "Contrato"},
        {"alert_wallet", "Carteira"},
        {"alert_transaction", "Transação"},

        // --- Menu principal ---
        {"menu_title", "🚨 <b>Wallet Tracker</b>"},
        {"menu_add_wallet", "➕ Adicionar carteira"},
        {"menu_my_wallets", "💼 Minhas carteiras"},
        {"menu_alert_threshold", "💰 Valor mínimo do alerta"},
        {"menu_account", "👤 Minha conta"},
        {"account_title", "👤 <b>Minha conta</b>"},
        {"account_desc", "Suas carteiras monitoradas e o que elas têm agora."},
        {"menu_hold", "💎 Portfólio"},
        {"hold_title", "💎 <b>Portfólio</b>"},
        {"hold_choose", "Escolha uma carteira para ver o que ela tem agora:"},
        {"hold_loading", "⏳ Lendo os saldos da blockchain, isso leva alguns segundos..."},
        {"hold_total", "Valor total"},
        {"hold_coins", "Moedas na carteira"},
        {"hold_empty", "Nenhuma moeda de $10 ou mais encontrada nesta carteira."},
        {"hold_illiquid", "As posições marcadas são maiores que o pool delas: o preço de mercado exibido não é alcançável na venda."},
        {"hold_partial", "⚠️ Alguns saldos não puderam ser lidos agora, o total pode estar incompleto."},
        {"hold_dust_note", "Posições abaixo de $10 não são exibidas."},
        {"hold_no_history", "Ainda não vimos esta carteira operar, então não há o que verificar além do saldo nativo."},
        {"menu_top_traders", "🏆 Melhores traders"},
        {"menu_premium", "⭐ Premium"},
        {"menu_languages", "🌐 Idioma"},
        {"menu_help", "❓ Ajuda"},
        {"menu_no_wallets", "Você ainda não monitora nenhuma carteira.\nToque em <b>Adicionar carteira</b> para começar a receber alertas."},
        {"menu_tracking_prefix", "Monitorando"},
        {"menu_alerts_above", "alertas a partir de"},
        {"back_button", "← Voltar"},
        {"cancel_button", "❌ Cancelar"},

        // --- Adicionar carteira ---
        {"add_wallet_title", "➕ <b>Adicionar carteira</b>\n\nEnvie o endereço da carteira que você quer monitorar — formato 0x..., 42 caracteres.\n\n💡 <b>Não sabe qual carteira adicionar?</b>\nA aba 🏆 <b>Melhores traders</b> abaixo lista as carteiras mais lucrativas dos últimos 30 dias: escolha qualquer uma e comece a monitorar com um toque.\nOu cole um endereço de um explorador de blocos ou de um serviço de análise."},
        {"add_wallet_addr_ok", "✅ Endereço aceito.\n\nAgora digite um nome para esta carteira — até 32 caracteres (por exemplo, \"Binance\"):"},
        {"add_wallet_invalid", "❌ Endereço de carteira inválido.\n\nO endereço deve começar com 0x e ter 42 caracteres. Digite um endereço válido ou toque em Cancelar."},
        {"add_wallet_success", "✅ <b>Carteira adicionada</b>"},
        {"add_wallet_name_label", "Nome:"},
        {"add_wallet_address_label", "Endereço:"},
        {"add_wallet_tracking_enabled", "Monitoramento ativado."},
        {"track_name_prompt", "🏷 Digite um nome para este trader:"},
        {"token_search_prompt", "🪙 <b>Melhor PnL por token</b>\n\nDigite o símbolo de um token (por exemplo <code>CAKE</code>) ou um endereço de contrato (<code>0x...</code>):"},
        {"token_search_empty", "❌ Digite o símbolo de um token ou um endereço de contrato, ou toque em Cancelar."},
        {"remove_confirm_title", "🗑️ <b>Remover carteira?</b>"},
        {"remove_confirm_notice", "Você deixará de receber alertas desta carteira."},
        {"remove_yes", "🗑️ Sim, remover"},
        {"toast_wallet_removed", "✅ Carteira removida"},

        // --- Valor mínimo do alerta ---
        {"err_invalid_number", "❌ Número inválido."},
        {"err_threshold_positive", "❌ O valor mínimo deve ser positivo."},
        {"err_threshold_too_small", "❌ O valor mínimo de alerta é $50. Digite $50 ou mais."},
        {"err_threshold_too_large", "❌ O valor é alto demais."},
        {"err_threshold_decimals", "❌ Use no máximo 2 casas decimais (por exemplo, 7500.50)."},
        {"threshold_retry_hint", "\n\nDigite um valor válido (por exemplo, 7500 ou 7500.50) ou toque em Cancelar."},
        {"threshold_unchanged", "ℹ️ O valor atual já é"},
        {"threshold_updated", "✅ <b>Valor mínimo do alerta atualizado</b>\n\nValor atual:"},
        {"threshold_save_failed", "❌ Não foi possível salvar o valor. Tente novamente."},
        {"threshold_title", "💰 <b>Valor mínimo do alerta</b>"},
        {"threshold_desc", "Você só receberá alertas de transações iguais ou acima deste valor."},
        {"threshold_current", "Valor atual:"},
        {"threshold_choose", "Escolha um valor pronto ou digite um personalizado:"},
        {"threshold_custom_btn", "✏️ Valor personalizado"},
        {"threshold_custom_title", "💰 <b>Valor personalizado</b>\n\nDigite o valor mínimo do alerta em USD — a partir de $50 (por exemplo, 7500 ou 7500.50):"},
        {"unknown_command", "🤔 Use o menu abaixo."},

        // --- Idioma ---
        {"lang_title", "🌐 <b>Idioma</b>"},
        {"lang_current", "Idioma atual:"},
        {"lang_choose", "Escolha o idioma dos alertas e dos menus:"},

        // --- Minhas carteiras ---
        {"rk_generating", "⏳ O ranking está sendo gerado.\n\nTente novamente em um minuto."},
        {"mw_no_wallets", "Você ainda não monitora nenhuma carteira."},
        {"mw_tap_add", "Toque em ➕ <b>Adicionar carteira</b> para começar."},
        {"mw_free_notice1", "ℹ️ Plano gratuito: os alertas ficam ativos apenas para a sua primeira carteira (🔔)."},
        {"mw_free_notice2", "Suas outras carteiras estão salvas (⏸) e serão reativadas com o Premium."},
        {"mw_upgrade", "⭐ Assinar o Premium"},
        {"ws_title", "📊 <b>Estatísticas da carteira</b>"},
        {"ws_rank", "Posição"},
        {"ws_not_in_ranking", "(fora do ranking de 30D)"},
        {"ws_winrate", "Acertos"},
        {"ws_trades_30d", "Operações (30D)"},
        {"ws_last_trade", "Última operação"},

        // --- Rankings ---
        {"rk_top_pnl_30d", "Maiores PnL (30D)"},
        {"rk_top_traders_30d", "Melhores traders (30D)"},
        {"rk_top_roi_30d", "Maiores ROI (30D)"},
        {"rk_roi_per_trade", "ROI por operação"},
        {"rk_top_winrate_30d", "Maiores taxas de acerto (30D)"},
        {"rk_most_active_30d", "Mais ativos (30D)"},
        {"rk_smart_contract", "Contrato inteligente"},
        {"rk_no_wallets_min_trades1", "Nenhuma carteira com pelo menos"},
        {"rk_no_wallets_min_trades2", "operações encerradas nos últimos 30 dias."},
        {"rk_no_completed_trades", "Ainda não há operações encerradas nos últimos 30 dias."},
        {"rk_prev", "⬅️ Anterior"},
        {"rk_next", "Próxima ➡️"},
        {"rk_track", "➕ Monitorar"},
        {"rk_avg_hold", "Tempo médio"},
        {"unit_day", "d"},
        {"unit_hour", "h"},
        {"unit_min", "min"},
        {"unit_sec", "s"},
        {"rk_trades", "Operações"},
        {"rk_unlock_top100", "🔒 Libere o Top 100 com o Premium."},
        {"rk_choose_ranking", "Escolha um ranking:"},
        {"rk_btn_top_pnl", "💵 Maiores PnL"},
        {"rk_btn_top_roi", "📈 Maiores ROI"},
        {"rk_btn_top_winrate", "🎯 Maiores taxas de acerto"},
        {"rk_btn_most_active", "🔄 Mais ativos"},
        {"rk_btn_top_pnl_by_token", "🪙 Maiores PnL por token"},
        {"rk_unknown_token1", "❌ Token desconhecido:"},
        {"rk_unknown_token2", "Informe o endereço do contrato diretamente, ou um símbolo que o bot já tenha visto em alguma operação."},
        {"rk_expired", "⏳ Este ranking expirou. Busque o token novamente pelo menu."},

        // --- Ajuda ---
        {"help_title", "❓ <b>Ajuda</b>"},
        {"help_intro", "🏆 Descubra os melhores traders on-chain, monitore carteiras e receba alertas de operações em tempo real nas redes disponíveis."},
        {"help_commands", "<b>Use os botões do menu para:</b>"},
        {"help_menu_add", "➕ Adicionar carteira — monitorar uma carteira nova"},
        {"help_menu_mywallets", "💼 Minhas carteiras — ver e gerenciar as carteiras monitoradas"},
        {"help_menu_threshold", "💰 Valor mínimo do alerta — definir o valor mínimo"},
        {"help_menu_top", "🏆 Melhores traders — ver o ranking de carteiras por resultado"},
        {"help_menu_premium", "⭐ Premium — ver os planos Premium"},
        {"help_menu_languages", "🌐 Idioma — trocar de idioma"},
        {"help_premium_title", "⭐ <b>Premium</b>"},
        {"help_premium_1", "• Acesso completo ao Top 100 de traders"},
        {"help_premium_2", "• Monitoramento de até 50 carteiras"},
        {"help_premium_3", "• Recursos avançados"},
        {"help_premium_4", "• Acesso prioritário às novidades"},
        {"help_disclaimer", "⚠️ <b>Aviso</b>\nO bot mostra transações on-chain que já aconteceram. É um serviço de informação, não é recomendação de investimento nem convite a operar. Resultados passados de uma carteira não preveem os futuros. Operar com alavancagem pode custar todo o seu depósito. As decisões são suas e o risco é seu."},
        {"help_support", "📞 Suporte: @WalletTrackerHelp"},
        {"help_channel", "📢 Canal: t.me/WalletTrackerOfficial"},
        {"help_footer", "Use o menu principal para acessar rapidamente todos os recursos."},

        // --- Premium ---
        {"pr_active_title", "⭐ <b>Premium ativo</b>"},
        {"pr_service_account", "Conta de serviço — o acesso Premium é permanente."},
        {"pr_valid_until_inline", "Sua assinatura é válida até"},
        {"pr_days_left", "dias restantes:"},
        {"pr_active_benefits", "Você tem acesso ao monitoramento de até 50 carteiras e ao Top 100 de traders completo."},
        {"pr_renew", "🔄 Renovar o Premium"},
        {"pr_title", "⭐ <b>Wallet Tracker Premium</b>"},
        {"pr_unlock", "Aproveite todo o potencial do Wallet Tracker."},
        {"pr_includes", "<b>O Premium inclui:</b>"},
        {"pr_50_wallets", "✅ Monitoramento de até 50 carteiras em vez de 1 do plano gratuito"},
        {"pr_top100", "✅ Acesso ao Top 100 de traders completo (o Top 30 é gratuito)"},
        {"pr_subscription_label", "<b>Assinatura:</b> 30 dias"},
        {"pr_price_label", "<b>Preço:</b>"},
        {"pr_buy", "⭐ Comprar o Premium"},
        {"pr_limit_title", "⚠️ <b>Limite de carteiras atingido</b>"},
        {"pr_limit_free", "O plano gratuito permite monitorar apenas 1 carteira."},
        {"pr_limit_upgrade", "Assine o Premium para monitorar até 50 carteiras."},
        {"invoice_title", "Wallet Tracker Premium"},
        {"invoice_description", "Assinatura Premium de 30 dias"},
        {"invoice_price_label", "Premium (30 dias)"},
        {"invoice_unknown_product", "Produto desconhecido. Tente novamente."},
        {"payments_unavailable", "Os pagamentos estão temporariamente indisponíveis. Tente mais tarde."},
        {"payment_success_title", "✅ Pagamento concluído!"},
        {"payment_success_activated", "O Wallet Tracker Premium foi ativado."},
        {"payment_success_duration", "Válido por 30 dias."},

        // --- Limites e erros ---
        {"limit_50_reached", "⚠️ Você atingiu o limite de 50 carteiras monitoradas."},
        {"already_tracking", "⚠️ Você já monitora esta carteira."},
        {"toast_already_tracking", "✅ Já monitorada"},
        {"wallet_limit_50_short", "⚠️ Limite de carteiras atingido (50)"},
        {"free_plan_1_wallet", "⚠️ O plano gratuito permite monitorar apenas 1 carteira. Assine o Premium — toque em ⭐ Premium no menu."},
        {"already_tracking_retry", "⚠️ Você já monitora esta carteira.\n\nDigite outro endereço ou toque em Cancelar."},
        {"wallet_bot_banned", "🤖 Esta carteira foi marcada como bot e excluída do ranking em definitivo. A conta de serviço não pode monitorá-la.\n\nDigite outro endereço ou toque em Cancelar."},
        {"toast_invalid_address", "❌ Endereço inválido."},
        {"track_now_tracked", "✅ A carteira"},
        {"track_now_tracked_suffix", "já está sendo monitorada."},
        {"generic_error_retry", "❌ Algo deu errado, tente novamente."},
        {"err_invalid_address", "❌ Endereço de carteira inválido."},
        {"err_loading_wallet", "❌ Erro ao carregar a carteira."},
        {"err_loading_wallets", "❌ Erro ao carregar as carteiras."},
        {"op_cancelled", "❌ Operação cancelada."},
        {"err_invoice_failed", "❌ Não foi possível gerar a cobrança. Tente mais tarde."},
        {"err_user_limit", "⚠️ Limite de usuários atingido. Tente mais tarde."},
        {"err_wallet_not_found", "❌ A carteira não está na sua lista."},
        {"rename_title", "✏️ <b>Renomear carteira</b>"},
        {"rename_current_name", "Nome atual:"},
        {"rename_enter_new", "Digite um nome novo:"},
        {"rename_success", "✅ <b>Carteira renomeada</b>"},
        {"rename_new_name", "Nome novo:"},
        {"err_name_empty", "❌ O nome não pode ficar vazio.\n\nDigite um nome ou toque em Cancelar."},
        {"err_name_too_long", "❌ O nome é longo demais (máx. 32 caracteres).\n\nDigite um nome mais curto ou toque em Cancelar."},

        // --- Futuros perpétuos da Hyperliquid ---
        {"hl_open_long", "ABRIU COMPRADO"},
        {"hl_close_long", "ENCERROU COMPRADO"},
        {"hl_open_short", "ABRIU VENDIDO"},
        {"hl_close_short", "ENCERROU VENDIDO"},
        {"hl_flip", "INVERTEU A POSIÇÃO"},
        {"hl_liquidated", "LIQUIDADO"},
        {"hl_trade", "OPERAÇÃO PERP"},
        {"hl_trade_size", "Tamanho da operação"},
        {"hl_position_size", "Tamanho da posição"},
        {"hl_collateral", "Margem"},
        {"hl_of_account", "da conta"},
        {"hl_position_closed", "Posição encerrada por completo"},
        {"hl_leverage", "Alavancagem"},
        {"hl_cross", "cruzada"},
        {"hl_isolated", "isolada"},
        {"hl_price", "Preço"},
        {"hl_qty", "Quantidade"},
        {"hl_pnl", "PnL realizado"},
        {"hl_liq", "Liquidação"},
        {"hl_account", "Valor da conta"},
        {"hl_venue", "Plataforma"},
        {"hl_venue_title", "Melhores traders"},
        {"hl_venue_choose", "Escolha a plataforma:\n<i>Spot na BSC ou futuros perpétuos na Hyperliquid</i>"},
        {"hl_venue_spot", "🟡 BSC — Spot"},
        {"hl_venue_perp", "🔵 Hyperliquid — Futuros"},
        {"hl_rk_title", "melhores traders, 30 dias"},
        {"hl_rk_choose", "Escolha um ranking:"},
        {"hl_locked_body", "Os futuros perpétuos estão disponíveis com o Premium.\n\nVocê recebe a alavancagem, a margem e o preço de liquidação de cada operação, o PnL realizado direto da corretora e o ranking de traders de 30 dias."},
        {"hl_rk_leverage", "Alavancagem média"},
        {"hl_rk_roi_account", "ROI sobre o depósito"},
        {"hl_rk_empty", "Ainda não há dados: o ranking precisa de pelo menos 5 operações encerradas por carteira em 30 dias."},
    };
    return t;
}

} // namespace

const char* trPt(const std::string& key) {
    const auto& t = tablePt();
    auto it = t.find(key);
    return it == t.end() ? nullptr : it->second;
}
