#include "ru.h"
#include <unordered_map>

// ============================== Français ==============================
// Отдельный файл на язык - см. lang_es.cpp. Ключа может не быть: tr() тогда
// покажет английский, а не пустоту.
//
// Две терминологические развилки решены так:
//   "portefeuille" - кошелёк, а раздел с активами назван "Avoirs". По-французски
//   портфель тоже "portefeuille", и два разных экрана назывались бы одинаково.
//   long / short оставлены как есть: во французской крипте их не переводят,
//   "position longue" звучит по-учебному и длиннее вдвое.

namespace {

const std::unordered_map<std::string, const char*>& tableFr() {
    static const std::unordered_map<std::string, const char*> t = {
        // --- Types d'opérations dans les alertes ---
        {"alert_buy", "ACHAT"},
        {"alert_sell", "VENTE"},
        {"alert_transfer", "TRANSFERT"},
        {"alert_add_liquidity", "AJOUT DE LIQUIDITÉ"},
        {"alert_remove_liquidity", "RETRAIT DE LIQUIDITÉ"},
        {"alert_collect_fees", "COLLECTE DES FRAIS"},
        {"alert_wrap", "WRAP"},
        {"alert_unwrap", "UNWRAP"},
        {"alert_bridge_out", "SORTIE PAR PONT"},
        {"alert_bridge_in", "ENTRÉE PAR PONT"},
        {"alert_arbitrage", "ARBITRAGE"},
        {"alert_amount", "Montant"},
        {"alert_token", "Token"},
        {"alert_qty", "Quantité"},
        {"alert_buy_price", "Prix d'achat"},
        {"alert_sell_price", "Prix de vente"},
        {"alert_gas", "Frais de réseau"},
        {"alert_spent", "Dépensé"},
        {"alert_received", "Reçu"},
        {"alert_contract", "Contrat"},
        {"alert_wallet", "Portefeuille"},
        {"alert_transaction", "Transaction"},

        // --- Menu principal ---
        {"menu_title", "🚨 <b>Wallet Tracker</b>"},
        {"menu_add_wallet", "➕ Ajouter un portefeuille"},
        {"menu_my_wallets", "💼 Mes portefeuilles"},
        {"menu_alert_threshold", "💰 Seuil d'alerte"},
        {"menu_account", "👤 Mon compte"},
        {"account_title", "👤 <b>Mon compte</b>"},
        {"account_desc", "Les portefeuilles que vous suivez et ce qu'ils détiennent en ce moment."},
        {"menu_hold", "💎 Avoirs"},
        {"hold_title", "💎 <b>Avoirs</b>"},
        {"hold_choose", "Choisissez un portefeuille pour voir ce qu'il détient en ce moment :"},
        {"hold_loading", "⏳ Lecture des soldes sur la blockchain, cela prend quelques secondes..."},
        {"hold_total", "Valeur totale"},
        {"hold_coins", "Jetons détenus"},
        {"hold_empty", "Aucun jeton d'une valeur de 10 $ ou plus dans ce portefeuille."},
        {"hold_illiquid", "Les positions marquées dépassent la taille de leur pool : le prix affiché n'est pas atteignable à la vente."},
        {"hold_partial", "⚠️ Certains soldes n'ont pas pu être lus pour l'instant, le total peut être incomplet."},
        {"hold_dust_note", "Les positions inférieures à 10 $ ne sont pas affichées."},
        {"hold_no_history", "Nous n'avons pas encore vu ce portefeuille négocier, il n'y a donc rien à vérifier hormis le solde natif."},
        {"menu_top_traders", "🏆 Meilleurs traders"},
        {"menu_premium", "⭐ Premium"},
        {"menu_languages", "🌐 Langue"},
        {"menu_help", "❓ Aide"},
        {"menu_no_wallets", "Vous ne suivez encore aucun portefeuille.\nAppuyez sur <b>Ajouter un portefeuille</b> pour recevoir des alertes."},
        {"menu_tracking_prefix", "Suivi"},
        {"menu_alerts_above", "alertes à partir de"},
        {"back_button", "← Retour"},
        {"cancel_button", "❌ Annuler"},

        // --- Ajouter un portefeuille ---
        {"add_wallet_title", "➕ <b>Ajouter un portefeuille</b>\n\nEnvoyez l'adresse du portefeuille que vous souhaitez suivre — format 0x..., 42 caractères.\n\n💡 <b>Vous ne savez pas quel portefeuille ajouter ?</b>\nL'onglet 🏆 <b>Meilleurs traders</b> ci-dessous classe les portefeuilles les plus rentables des 30 derniers jours : choisissez-en un et suivez-le en un appui.\nOu collez une adresse depuis un explorateur de blocs ou un service d'analyse."},
        {"add_wallet_addr_ok", "✅ Adresse acceptée.\n\nSaisissez maintenant un nom pour ce portefeuille — 32 caractères maximum (par exemple, \"Binance\") :"},
        {"add_wallet_invalid", "❌ Adresse de portefeuille invalide.\n\nL'adresse doit commencer par 0x et compter 42 caractères. Saisissez une adresse valide ou appuyez sur Annuler."},
        {"add_wallet_success", "✅ <b>Portefeuille ajouté</b>"},
        {"add_wallet_name_label", "Nom :"},
        {"add_wallet_address_label", "Adresse :"},
        {"add_wallet_tracking_enabled", "Suivi activé."},
        {"track_name_prompt", "🏷 Saisissez un nom pour ce trader :"},
        {"token_search_prompt", "🪙 <b>Meilleur PnL par jeton</b>\n\nSaisissez le symbole d'un jeton (par exemple <code>CAKE</code>) ou une adresse de contrat (<code>0x...</code>) :"},
        {"token_search_empty", "❌ Saisissez le symbole d'un jeton ou une adresse de contrat, ou appuyez sur Annuler."},
        {"remove_confirm_title", "🗑️ <b>Supprimer le portefeuille ?</b>"},
        {"remove_confirm_notice", "Vous ne recevrez plus d'alertes pour ce portefeuille."},
        {"remove_yes", "🗑️ Oui, supprimer"},
        {"toast_wallet_removed", "✅ Portefeuille supprimé"},

        // --- Seuil d'alerte ---
        {"err_invalid_number", "❌ Nombre invalide."},
        {"err_threshold_positive", "❌ Le seuil doit être positif."},
        {"err_threshold_too_small", "❌ Le seuil minimal d'alerte est de 50 $. Saisissez 50 $ ou plus."},
        {"err_threshold_too_large", "❌ Le seuil est trop élevé."},
        {"err_threshold_decimals", "❌ Utilisez au maximum 2 décimales (par exemple, 7500.50)."},
        {"threshold_retry_hint", "\n\nSaisissez un montant valide (par exemple, 7500 ou 7500.50) ou appuyez sur Annuler."},
        {"threshold_unchanged", "ℹ️ Le seuil actuel est déjà de"},
        {"threshold_updated", "✅ <b>Seuil d'alerte mis à jour</b>\n\nSeuil actuel :"},
        {"threshold_save_failed", "❌ Impossible d'enregistrer le seuil. Réessayez."},
        {"threshold_title", "💰 <b>Seuil d'alerte</b>"},
        {"threshold_desc", "Vous ne recevrez d'alertes que pour les transactions égales ou supérieures à ce montant."},
        {"threshold_current", "Seuil actuel :"},
        {"threshold_choose", "Choisissez un montant prédéfini ou saisissez le vôtre :"},
        {"threshold_custom_btn", "✏️ Montant personnalisé"},
        {"threshold_custom_title", "💰 <b>Seuil personnalisé</b>\n\nSaisissez le montant minimal d'alerte en USD — à partir de 50 $ (par exemple, 7500 ou 7500.50) :"},
        {"unknown_command", "🤔 Utilisez le menu ci-dessous."},

        // --- Langue ---
        {"lang_title", "🌐 <b>Langue</b>"},
        {"lang_current", "Langue actuelle :"},
        {"lang_choose", "Choisissez la langue des alertes et des menus :"},

        // --- Mes portefeuilles ---
        {"rk_generating", "⏳ Le classement est en cours de génération.\n\nRéessayez dans une minute."},
        {"mw_no_wallets", "Vous ne suivez encore aucun portefeuille."},
        {"mw_tap_add", "Appuyez sur ➕ <b>Ajouter un portefeuille</b> pour commencer."},
        {"mw_free_notice1", "ℹ️ Offre gratuite : les alertes ne sont actives que pour votre premier portefeuille (🔔)."},
        {"mw_free_notice2", "Vos autres portefeuilles sont conservés (⏸) et seront réactivés avec Premium."},
        {"mw_upgrade", "⭐ Passer à Premium"},
        {"ws_title", "📊 <b>Statistiques du portefeuille</b>"},
        {"ws_rank", "Rang"},
        {"ws_not_in_ranking", "(hors classement 30J)"},
        {"ws_winrate", "Taux de réussite"},
        {"ws_trades_30d", "Opérations (30J)"},
        {"ws_last_trade", "Dernière opération"},

        // --- Classements ---
        {"rk_top_pnl_30d", "Meilleurs PnL (30J)"},
        {"rk_top_traders_30d", "Meilleurs traders (30J)"},
        {"rk_top_roi_30d", "Meilleurs ROI (30J)"},
        {"rk_roi_per_trade", "ROI par opération"},
        {"rk_top_winrate_30d", "Meilleurs taux de réussite (30J)"},
        {"rk_most_active_30d", "Les plus actifs (30J)"},
        {"rk_smart_contract", "Contrat intelligent"},
        {"rk_no_wallets_min_trades1", "Aucun portefeuille avec au moins"},
        {"rk_no_wallets_min_trades2", "opérations clôturées ces 30 derniers jours."},
        {"rk_no_completed_trades", "Aucune opération clôturée ces 30 derniers jours pour l'instant."},
        {"rk_prev", "⬅️ Précédent"},
        {"rk_next", "Suivant ➡️"},
        {"rk_track", "➕ Suivre"},
        {"rk_avg_hold", "Durée moyenne"},
        {"unit_day", "j"},
        {"unit_hour", "h"},
        {"unit_min", "min"},
        {"unit_sec", "s"},
        {"rk_trades", "Opérations"},
        {"rk_unlock_top100", "🔒 Débloquez le Top 100 avec Premium."},
        {"rk_choose_ranking", "Choisissez un classement :"},
        {"rk_btn_top_pnl", "💵 Meilleurs PnL"},
        {"rk_btn_top_roi", "📈 Meilleurs ROI"},
        {"rk_btn_top_winrate", "🎯 Meilleurs taux de réussite"},
        {"rk_btn_most_active", "🔄 Les plus actifs"},
        {"rk_btn_top_pnl_by_token", "🪙 Meilleurs PnL par jeton"},
        {"rk_unknown_token1", "❌ Jeton inconnu :"},
        {"rk_unknown_token2", "Indiquez directement l'adresse du contrat, ou un symbole que le bot a déjà vu dans une opération."},
        {"rk_expired", "⏳ Ce classement a expiré. Recherchez le jeton à nouveau depuis le menu."},

        // --- Aide ---
        {"help_title", "❓ <b>Aide</b>"},
        {"help_intro", "🏆 Découvrez les meilleurs traders on-chain, suivez des portefeuilles et recevez des alertes en temps réel sur les réseaux pris en charge."},
        {"help_commands", "<b>Utilisez les boutons du menu pour :</b>"},
        {"help_menu_add", "➕ Ajouter un portefeuille — suivre un nouveau portefeuille"},
        {"help_menu_mywallets", "💼 Mes portefeuilles — consulter et gérer les portefeuilles suivis"},
        {"help_menu_threshold", "💰 Seuil d'alerte — définir le montant minimal"},
        {"help_menu_top", "🏆 Meilleurs traders — voir le classement des portefeuilles par résultat"},
        {"help_menu_premium", "⭐ Premium — voir les offres Premium"},
        {"help_menu_languages", "🌐 Langue — changer de langue"},
        {"help_premium_title", "⭐ <b>Premium</b>"},
        {"help_premium_1", "• Accès complet au Top 100 des traders"},
        {"help_premium_2", "• Suivi de 50 portefeuilles"},
        {"help_premium_3", "• Fonctions avancées"},
        {"help_premium_4", "• Accès prioritaire aux nouveautés"},
        {"help_disclaimer", "⚠️ <b>Avertissement</b>\nLe bot affiche des transactions on-chain déjà réalisées. Il s'agit d'un service d'information, non d'un conseil en investissement ni d'une incitation à négocier. Les résultats passés d'un portefeuille ne préjugent pas des résultats futurs. Le trading avec effet de levier peut vous coûter la totalité de votre dépôt. Vous décidez seul et assumez seul le risque."},
        {"help_support", "📞 Assistance : @WalletTrackerHelp"},
        {"help_channel", "📢 Canal : t.me/WalletTrackerOfficial"},
        {"help_footer", "Utilisez le menu principal pour accéder rapidement à toutes les fonctions."},

        // --- Premium ---
        {"pr_active_title", "⭐ <b>Premium actif</b>"},
        {"pr_service_account", "Compte de service — l'accès Premium est permanent."},
        {"pr_valid_until_inline", "Votre abonnement est valable jusqu'au"},
        {"pr_days_left", "jours restants :"},
        {"pr_active_benefits", "Vous avez accès au suivi de 50 portefeuilles et au Top 100 des traders complet."},
        {"pr_renew", "🔄 Renouveler Premium"},
        {"pr_title", "⭐ <b>Wallet Tracker Premium</b>"},
        {"pr_unlock", "Exploitez tout le potentiel de Wallet Tracker."},
        {"pr_includes", "<b>Premium comprend :</b>"},
        {"pr_50_wallets", "✅ Suivi de 50 portefeuilles au lieu d'un seul dans l'offre gratuite"},
        {"pr_top100", "✅ Accès au Top 100 des traders complet (le Top 30 est gratuit)"},
        {"pr_subscription_label", "<b>Abonnement :</b> 30 jours"},
        {"pr_price_label", "<b>Prix :</b>"},
        {"pr_buy", "⭐ Acheter Premium"},
        {"pr_limit_title", "⚠️ <b>Limite de portefeuilles atteinte</b>"},
        {"pr_limit_free", "L'offre gratuite permet de suivre un seul portefeuille."},
        {"pr_limit_upgrade", "Passez à Premium pour suivre jusqu'à 50 portefeuilles."},
        {"invoice_title", "Wallet Tracker Premium"},
        {"invoice_description", "Abonnement Premium de 30 jours"},
        {"invoice_price_label", "Premium (30 jours)"},
        {"invoice_unknown_product", "Produit inconnu. Réessayez."},
        {"payments_unavailable", "Les paiements sont temporairement indisponibles. Réessayez plus tard."},
        {"payment_success_title", "✅ Paiement effectué !"},
        {"payment_success_activated", "Wallet Tracker Premium a été activé."},
        {"payment_success_duration", "Valable 30 jours."},

        // --- Limites et erreurs ---
        {"limit_50_reached", "⚠️ Vous avez atteint la limite de 50 portefeuilles suivis."},
        {"already_tracking", "⚠️ Vous suivez déjà ce portefeuille."},
        {"toast_already_tracking", "✅ Déjà suivi"},
        {"wallet_limit_50_short", "⚠️ Limite de portefeuilles atteinte (50)"},
        {"free_plan_1_wallet", "⚠️ L'offre gratuite permet de suivre un seul portefeuille. Passez à Premium — appuyez sur ⭐ Premium dans le menu."},
        {"already_tracking_retry", "⚠️ Vous suivez déjà ce portefeuille.\n\nSaisissez une autre adresse ou appuyez sur Annuler."},
        {"wallet_bot_banned", "🤖 Ce portefeuille a été signalé comme bot et définitivement exclu du classement. Le compte de service ne peut pas le suivre.\n\nSaisissez une autre adresse ou appuyez sur Annuler."},
        {"toast_invalid_address", "❌ Adresse invalide."},
        {"track_now_tracked", "✅ Le portefeuille"},
        {"track_now_tracked_suffix", "est désormais suivi."},
        {"generic_error_retry", "❌ Une erreur est survenue, réessayez."},
        {"err_invalid_address", "❌ Adresse de portefeuille invalide."},
        {"err_loading_wallet", "❌ Erreur lors du chargement du portefeuille."},
        {"err_loading_wallets", "❌ Erreur lors du chargement des portefeuilles."},
        {"op_cancelled", "❌ Opération annulée."},
        {"err_invoice_failed", "❌ Impossible de créer la facture. Réessayez plus tard."},
        {"err_user_limit", "⚠️ Limite d'utilisateurs atteinte. Réessayez plus tard."},
        {"err_wallet_not_found", "❌ Ce portefeuille ne figure pas dans votre liste."},
        {"rename_title", "✏️ <b>Renommer le portefeuille</b>"},
        {"rename_current_name", "Nom actuel :"},
        {"rename_enter_new", "Saisissez un nouveau nom :"},
        {"rename_success", "✅ <b>Portefeuille renommé</b>"},
        {"rename_new_name", "Nouveau nom :"},
        {"err_name_empty", "❌ Le nom ne peut pas être vide.\n\nSaisissez un nom ou appuyez sur Annuler."},
        {"err_name_too_long", "❌ Le nom est trop long (32 caractères maximum).\n\nSaisissez un nom plus court ou appuyez sur Annuler."},

        // --- Futures perpétuels Hyperliquid ---
        {"hl_open_long", "LONG OUVERT"},
        {"hl_close_long", "LONG CLÔTURÉ"},
        {"hl_open_short", "SHORT OUVERT"},
        {"hl_close_short", "SHORT CLÔTURÉ"},
        {"hl_flip", "POSITION INVERSÉE"},
        {"hl_liquidated", "LIQUIDÉ"},
        {"hl_trade", "OPÉRATION PERP"},
        {"hl_trade_size", "Taille de l'opération"},
        {"hl_position_size", "Taille de la position"},
        {"hl_collateral", "Marge"},
        {"hl_of_account", "du compte"},
        {"hl_position_closed", "Position entièrement clôturée"},
        {"hl_leverage", "Effet de levier"},
        {"hl_cross", "croisée"},
        {"hl_isolated", "isolée"},
        {"hl_price", "Prix"},
        {"hl_qty", "Quantité"},
        {"hl_pnl", "PnL réalisé"},
        {"hl_liq", "Liquidation"},
        {"hl_account", "Valeur du compte"},
        {"hl_venue", "Plateforme"},
        {"hl_venue_title", "Meilleurs traders"},
        {"hl_venue_choose", "Choisissez la plateforme :\n<i>Spot sur BSC ou futures perpétuels sur Hyperliquid</i>"},
        {"hl_venue_spot", "🟡 BSC — Spot"},
        {"hl_venue_perp", "🔵 Hyperliquid — Futures"},
        {"hl_rk_title", "meilleurs traders, 30 jours"},
        {"hl_rk_choose", "Choisissez un classement :"},
        {"hl_locked_body", "Les futures perpétuels sont accessibles avec Premium.\n\nVous obtenez l'effet de levier, la marge et le prix de liquidation de chaque opération, le PnL réalisé directement depuis la plateforme, ainsi que le classement des traders sur 30 jours."},
        {"hl_rk_leverage", "Levier moyen"},
        {"hl_rk_roi_account", "ROI sur le dépôt"},
        {"hl_rk_empty", "Pas encore de données : le classement nécessite au moins 5 opérations clôturées par portefeuille sur 30 jours."},
    };
    return t;
}

} // namespace

const char* trFr(const std::string& key) {
    const auto& t = tableFr();
    auto it = t.find(key);
    return it == t.end() ? nullptr : it->second;
}
