#include "ru.h"
#include <unordered_map>

// ============================== Türkçe ==============================
// Отдельный файл на язык - см. lang_es.cpp. Ключа может не быть: tr() тогда
// покажет английский, а не пустоту.
//
// Турецкий агглютинативный: смысл достраивается окончаниями, и подставлять
// слова в готовую фразу нельзя так же свободно, как в европейских языках.
// Поэтому части фраз, которые в коде склеиваются из двух ключей, переведены с
// оглядкой на итоговый порядок слов, а не пословно.
//
// Заимствования, ставшие стандартом на биржах - trader, long, short, spot,
// PnL - оставлены как есть.

namespace {

const std::unordered_map<std::string, const char*>& tableTr() {
    static const std::unordered_map<std::string, const char*> t = {
        // --- Uyarılardaki işlem türleri ---
        {"alert_buy", "ALIM"},
        {"alert_sell", "SATIM"},
        {"alert_transfer", "TRANSFER"},
        {"alert_add_liquidity", "LİKİDİTE EKLEME"},
        {"alert_remove_liquidity", "LİKİDİTE ÇEKME"},
        {"alert_collect_fees", "ÜCRET TAHSİLİ"},
        {"alert_wrap", "WRAP"},
        {"alert_unwrap", "UNWRAP"},
        {"alert_bridge_out", "KÖPRÜDEN ÇIKIŞ"},
        {"alert_bridge_in", "KÖPRÜDEN GİRİŞ"},
        {"alert_arbitrage", "ARBİTRAJ"},
        {"alert_amount", "Tutar"},
        {"alert_token", "Token"},
        {"alert_qty", "Miktar"},
        {"alert_buy_price", "Alış fiyatı"},
        {"alert_sell_price", "Satış fiyatı"},
        {"alert_gas", "Ağ ücreti"},
        {"alert_spent", "Harcanan"},
        {"alert_received", "Alınan"},
        {"alert_contract", "Sözleşme"},
        {"alert_wallet", "Cüzdan"},
        {"alert_transaction", "İşlem"},

        // --- Ana menü ---
        {"menu_title", "🚨 <b>Wallet Tracker</b>"},
        {"menu_add_wallet", "➕ Cüzdan ekle"},
        {"menu_my_wallets", "💼 Cüzdanlarım"},
        {"menu_alert_threshold", "💰 Uyarı eşiği"},
        {"menu_account", "👤 Hesabım"},
        {"account_title", "👤 <b>Hesabım</b>"},
        {"account_desc", "Takip ettiğin cüzdanlar ve şu anda ellerinde ne olduğu."},
        {"menu_hold", "💎 Portföy"},
        {"hold_title", "💎 <b>Portföy</b>"},
        {"hold_choose", "Şu anda ne tuttuğunu görmek için bir cüzdan seç:"},
        {"hold_loading", "⏳ Bakiyeler blok zincirinden okunuyor, bu birkaç saniye sürer..."},
        {"hold_total", "Toplam değer"},
        {"hold_coins", "Tutulan coinler"},
        {"hold_empty", "Bu cüzdanda 10 $ veya üzeri değerde coin bulunamadı."},
        {"hold_illiquid", "İşaretli pozisyonlar kendi havuzlarından büyük: gösterilen piyasa fiyatı satışta elde edilemez."},
        {"hold_partial", "⚠️ Bazı bakiyeler şu anda okunamadı, toplam eksik olabilir."},
        {"hold_dust_note", "10 $ altındaki pozisyonlar gösterilmiyor."},
        {"hold_no_history", "Bu cüzdanın işlem yaptığını henüz görmedik, bu yüzden yerel bakiye dışında kontrol edilecek bir şey yok."},
        {"menu_top_traders", "🏆 En iyi trader'lar"},
        {"menu_premium", "⭐ Premium"},
        {"menu_languages", "🌐 Dil"},
        {"menu_help", "❓ Yardım"},
        {"menu_no_wallets", "Henüz hiçbir cüzdanı takip etmiyorsun.\nUyarı almaya başlamak için <b>Cüzdan ekle</b>'ye dokun."},
        {"menu_tracking_prefix", "Takipte"},
        {"menu_alerts_above", "uyarı eşiği"},
        {"back_button", "← Geri"},
        {"cancel_button", "❌ İptal"},

        // --- Cüzdan ekleme ---
        {"add_wallet_title", "➕ <b>Cüzdan ekle</b>\n\nTakip etmek istediğin cüzdanın adresini gönder — 0x... biçiminde, 42 karakter.\n\n💡 <b>Hangi cüzdanı ekleyeceğini bilmiyor musun?</b>\nAşağıdaki 🏆 <b>En iyi trader'lar</b> sekmesi son 30 günün en kârlı cüzdanlarını sıralar: herhangi birini seç ve tek dokunuşla takibe al.\nYa da bir blok gezgininden veya analiz servisinden bir adres yapıştır."},
        {"add_wallet_addr_ok", "✅ Adres kabul edildi.\n\nŞimdi bu cüzdan için bir isim gir — en fazla 32 karakter (örneğin \"Binance\"):"},
        {"add_wallet_invalid", "❌ Geçersiz cüzdan adresi.\n\nAdres 0x ile başlamalı ve 42 karakter olmalı. Geçerli bir adres gir ya da İptal'e dokun."},
        {"add_wallet_success", "✅ <b>Cüzdan eklendi</b>"},
        {"add_wallet_name_label", "İsim:"},
        {"add_wallet_address_label", "Adres:"},
        {"add_wallet_tracking_enabled", "Takip açıldı."},
        {"track_name_prompt", "🏷 Bu trader için bir isim gir:"},
        {"token_search_prompt", "🪙 <b>Token bazında en iyi PnL</b>\n\nBir token sembolü (örneğin <code>CAKE</code>) ya da sözleşme adresi (<code>0x...</code>) gir:"},
        {"token_search_empty", "❌ Bir token sembolü veya sözleşme adresi gir, ya da İptal'e dokun."},
        {"remove_confirm_title", "🗑️ <b>Cüzdan silinsin mi?</b>"},
        {"remove_confirm_notice", "Bu cüzdan için uyarı almayı bırakacaksın."},
        {"remove_yes", "🗑️ Evet, sil"},
        {"toast_wallet_removed", "✅ Cüzdan silindi"},

        // --- Uyarı eşiği ---
        {"err_invalid_number", "❌ Geçersiz sayı."},
        {"err_threshold_positive", "❌ Eşik pozitif olmalı."},
        {"err_threshold_too_small", "❌ En düşük uyarı eşiği 50 $. 50 $ veya üzeri gir."},
        {"err_threshold_too_large", "❌ Eşik çok yüksek."},
        {"err_threshold_decimals", "❌ En fazla 2 ondalık basamak kullan (örneğin 7500.50)."},
        {"threshold_retry_hint", "\n\nGeçerli bir tutar gir (örneğin 7500 ya da 7500.50) ya da İptal'e dokun."},
        {"threshold_unchanged", "ℹ️ Mevcut eşik zaten"},
        {"threshold_updated", "✅ <b>Uyarı eşiği güncellendi</b>\n\nMevcut eşik:"},
        {"threshold_save_failed", "❌ Eşik kaydedilemedi. Tekrar dene."},
        {"threshold_title", "💰 <b>Uyarı eşiği</b>"},
        {"threshold_desc", "Yalnızca bu tutara eşit veya bundan büyük işlemler için uyarı alırsın."},
        {"threshold_current", "Mevcut eşik:"},
        {"threshold_choose", "Hazır bir değer seç ya da kendi tutarını gir:"},
        {"threshold_custom_btn", "✏️ Özel tutar"},
        {"threshold_custom_title", "💰 <b>Özel eşik</b>\n\nUyarı için en düşük tutarı USD olarak gir — 50 $ ve üzeri (örneğin 7500 ya da 7500.50):"},
        {"unknown_command", "🤔 Aşağıdaki menüyü kullan."},

        // --- Dil ---
        {"lang_title", "🌐 <b>Dil</b>"},
        {"lang_current", "Mevcut dil:"},
        {"lang_choose", "Uyarılar ve menüler için dili seç:"},

        // --- Cüzdanlarım ---
        {"rk_generating", "⏳ Sıralama hazırlanıyor.\n\nBir dakika sonra tekrar dene."},
        {"mw_no_wallets", "Henüz hiçbir cüzdanı takip etmiyorsun."},
        {"mw_tap_add", "Takibe başlamak için ➕ <b>Cüzdan ekle</b>'ye dokun."},
        {"mw_free_notice1", "ℹ️ Ücretsiz plan: uyarılar yalnızca ilk cüzdanın için açık (🔔)."},
        {"mw_free_notice2", "Diğer cüzdanların kayıtlı (⏸) ve Premium ile yeniden etkinleşecek."},
        {"mw_upgrade", "⭐ Premium'a geç"},
        {"ws_title", "📊 <b>Cüzdan istatistikleri</b>"},
        {"ws_rank", "Sıra"},
        {"ws_not_in_ranking", "(30G sıralamasında değil)"},
        {"ws_winrate", "Kazanma oranı"},
        {"ws_trades_30d", "İşlem (30G)"},
        {"ws_last_trade", "Son işlem"},

        // --- Sıralamalar ---
        {"rk_top_pnl_30d", "En yüksek PnL (30G)"},
        {"rk_top_traders_30d", "En iyi trader'lar (30G)"},
        {"rk_top_roi_30d", "En yüksek ROI (30G)"},
        {"rk_roi_per_trade", "İşlem başına ROI"},
        {"rk_top_winrate_30d", "En yüksek kazanma oranı (30G)"},
        {"rk_most_active_30d", "En aktif (30G)"},
        {"rk_smart_contract", "Akıllı sözleşme"},
        {"rk_no_wallets_min_trades1", "Son 30 günde en az"},
        {"rk_no_wallets_min_trades2", "kapanmış işlemi olan cüzdan yok."},
        {"rk_no_completed_trades", "Son 30 günde henüz kapanmış işlem yok."},
        {"rk_prev", "⬅️ Önceki"},
        {"rk_next", "Sonraki ➡️"},
        {"rk_track", "➕ Takip et"},
        {"rk_avg_hold", "Ortalama süre"},
        {"unit_day", "g"},
        {"unit_hour", "sa"},
        {"unit_min", "dk"},
        {"unit_sec", "sn"},
        {"rk_trades", "İşlem"},
        {"rk_unlock_top100", "🔒 Premium ile Top 100'ü aç."},
        {"rk_choose_ranking", "Bir sıralama seç:"},
        {"rk_btn_top_pnl", "💵 En yüksek PnL"},
        {"rk_btn_top_roi", "📈 En yüksek ROI"},
        {"rk_btn_top_winrate", "🎯 En yüksek kazanma oranı"},
        {"rk_btn_most_active", "🔄 En aktif"},
        {"rk_btn_top_pnl_by_token", "🪙 Token bazında en iyi PnL"},
        {"rk_unknown_token1", "❌ Bilinmeyen token:"},
        {"rk_unknown_token2", "Sözleşme adresini doğrudan ver, ya da botun bir işlemde daha önce gördüğü bir sembol kullan."},
        {"rk_expired", "⏳ Bu sıralamanın süresi doldu. Tokenı menüden yeniden ara."},

        // --- Yardım ---
        {"help_title", "❓ <b>Yardım</b>"},
        {"help_intro", "🏆 En iyi on-chain trader'ları keşfet, cüzdanları takip et ve desteklenen ağlarda işlem uyarılarını anında al."},
        {"help_commands", "<b>Menü düğmelerini şunlar için kullan:</b>"},
        {"help_menu_add", "➕ Cüzdan ekle — yeni bir cüzdanı takibe al"},
        {"help_menu_mywallets", "💼 Cüzdanlarım — takip ettiğin cüzdanları gör ve yönet"},
        {"help_menu_threshold", "💰 Uyarı eşiği — en düşük uyarı tutarını belirle"},
        {"help_menu_top", "🏆 En iyi trader'lar — cüzdanları sonuçlarına göre sıralı gör"},
        {"help_menu_premium", "⭐ Premium — Premium planlarını gör"},
        {"help_menu_languages", "🌐 Dil — dili değiştir"},
        {"help_premium_title", "⭐ <b>Premium</b>"},
        {"help_premium_1", "• Top 100 trader listesine tam erişim"},
        {"help_premium_2", "• 50 cüzdana kadar takip"},
        {"help_premium_3", "• Gelişmiş özellikler"},
        {"help_premium_4", "• Yeniliklere öncelikli erişim"},
        {"help_disclaimer", "⚠️ <b>Sorumluluk reddi</b>\nBot, zaten gerçekleşmiş on-chain işlemleri gösterir. Bu bir bilgi hizmetidir; yatırım tavsiyesi ya da işlem yapma çağrısı değildir. Bir cüzdanın geçmiş sonuçları gelecekteki sonuçlarını göstermez. Kaldıraçlı işlem tüm mevduatına mal olabilir. Kararı sen verirsin, riski sen taşırsın."},
        {"help_support", "📞 Destek: @WalletTrackerHelp"},
        {"help_channel", "📢 Kanal: t.me/WalletTrackerOfficial"},
        {"help_footer", "Tüm özelliklere hızlı erişim için ana menüyü kullan."},

        // --- Premium ---
        {"pr_active_title", "⭐ <b>Premium etkin</b>"},
        {"pr_service_account", "Servis hesabı — Premium erişimi kalıcıdır."},
        {"pr_valid_until_inline", "Aboneliğin şu tarihe kadar geçerli:"},
        {"pr_days_left", "kalan gün:"},
        {"pr_active_benefits", "50 cüzdana kadar takip ve Top 100 trader listesinin tamamı erişimine sahipsin."},
        {"pr_renew", "🔄 Premium'u yenile"},
        {"pr_title", "⭐ <b>Wallet Tracker Premium</b>"},
        {"pr_unlock", "Wallet Tracker'ın tüm gücünü aç."},
        {"pr_includes", "<b>Premium şunları içerir:</b>"},
        {"pr_50_wallets", "✅ Ücretsiz plandaki 1 cüzdan yerine 50 cüzdana kadar takip"},
        {"pr_top100", "✅ Top 100 trader listesinin tamamına erişim (Top 30 ücretsiz)"},
        {"pr_subscription_label", "<b>Abonelik:</b> 30 gün"},
        {"pr_price_label", "<b>Fiyat:</b>"},
        {"pr_buy", "⭐ Premium satın al"},
        {"pr_limit_title", "⚠️ <b>Cüzdan sınırına ulaşıldı</b>"},
        {"pr_limit_free", "Ücretsiz plan yalnızca 1 cüzdan takibine izin verir."},
        {"pr_limit_upgrade", "50 cüzdana kadar takip için Premium'a geç."},
        {"invoice_title", "Wallet Tracker Premium"},
        {"invoice_description", "30 günlük Premium abonelik"},
        {"invoice_price_label", "Premium (30 gün)"},
        {"invoice_unknown_product", "Bilinmeyen ürün. Tekrar dene."},
        {"payments_unavailable", "Ödemeler geçici olarak kullanılamıyor. Daha sonra tekrar dene."},
        {"payment_success_title", "✅ Ödeme başarılı!"},
        {"payment_success_activated", "Wallet Tracker Premium etkinleştirildi."},
        {"payment_success_duration", "30 gün geçerli."},

        // --- Sınırlar ve hatalar ---
        {"limit_50_reached", "⚠️ 50 cüzdan takibi sınırına ulaştın."},
        {"already_tracking", "⚠️ Bu cüzdanı zaten takip ediyorsun."},
        {"toast_already_tracking", "✅ Zaten takipte"},
        {"wallet_limit_50_short", "⚠️ Cüzdan sınırına ulaşıldı (50)"},
        {"free_plan_1_wallet", "⚠️ Ücretsiz plan yalnızca 1 cüzdan takibine izin verir. Premium'a geç — menüden ⭐ Premium'a dokun."},
        {"already_tracking_retry", "⚠️ Bu cüzdanı zaten takip ediyorsun.\n\nBaşka bir adres gir ya da İptal'e dokun."},
        {"wallet_bot_banned", "🤖 Bu cüzdan bot olarak işaretlendi ve sıralamadan kalıcı olarak çıkarıldı. Servis hesabı onu takip edemez.\n\nBaşka bir adres gir ya da İptal'e dokun."},
        {"toast_invalid_address", "❌ Geçersiz adres."},
        {"track_now_tracked", "✅ Cüzdan"},
        {"track_now_tracked_suffix", "artık takip ediliyor."},
        {"generic_error_retry", "❌ Bir şeyler ters gitti, tekrar dene."},
        {"err_invalid_address", "❌ Geçersiz cüzdan adresi."},
        {"err_loading_wallet", "❌ Cüzdan yüklenirken hata oluştu."},
        {"err_loading_wallets", "❌ Cüzdanlar yüklenirken hata oluştu."},
        {"op_cancelled", "❌ İşlem iptal edildi."},
        {"err_invoice_failed", "❌ Fatura oluşturulamadı. Daha sonra tekrar dene."},
        {"err_user_limit", "⚠️ Kullanıcı sınırına ulaşıldı. Daha sonra tekrar dene."},
        {"err_wallet_not_found", "❌ Cüzdan listende bulunamadı."},
        {"rename_title", "✏️ <b>Cüzdanı yeniden adlandır</b>"},
        {"rename_current_name", "Mevcut isim:"},
        {"rename_enter_new", "Yeni bir isim gir:"},
        {"rename_success", "✅ <b>Cüzdan yeniden adlandırıldı</b>"},
        {"rename_new_name", "Yeni isim:"},
        {"err_name_empty", "❌ İsim boş olamaz.\n\nBir isim gir ya da İptal'e dokun."},
        {"err_name_too_long", "❌ İsim çok uzun (en fazla 32 karakter).\n\nDaha kısa bir isim gir ya da İptal'e dokun."},

        // --- Hyperliquid vadeli işlemler ---
        {"hl_open_long", "LONG AÇTI"},
        {"hl_close_long", "LONG KAPATTI"},
        {"hl_open_short", "SHORT AÇTI"},
        {"hl_close_short", "SHORT KAPATTI"},
        {"hl_flip", "POZİSYONU ÇEVİRDİ"},
        {"hl_liquidated", "LİKİDE EDİLDİ"},
        {"hl_trade", "PERP İŞLEMİ"},
        {"hl_trade_size", "İşlem büyüklüğü"},
        {"hl_position_size", "Pozisyon büyüklüğü"},
        {"hl_collateral", "Teminat"},
        {"hl_of_account", "hesabın"},
        {"hl_position_closed", "Pozisyon tamamen kapatıldı"},
        {"hl_leverage", "Kaldıraç"},
        {"hl_cross", "cross"},
        {"hl_isolated", "izole"},
        {"hl_price", "Fiyat"},
        {"hl_qty", "Miktar"},
        {"hl_pnl", "Gerçekleşen PnL"},
        {"hl_liq", "Likidasyon"},
        {"hl_account", "Hesap değeri"},
        {"hl_venue", "Platform"},
        {"hl_venue_title", "En iyi trader'lar"},
        {"hl_venue_choose", "Platformu seç:\n<i>BSC'de spot ya da Hyperliquid'de vadeli işlemler</i>"},
        {"hl_venue_spot", "🟡 BSC — Spot"},
        {"hl_venue_perp", "🔵 Hyperliquid — Vadeli"},
        {"hl_rk_title", "en iyi trader'lar, 30 gün"},
        {"hl_rk_choose", "Bir sıralama seç:"},
        {"hl_locked_body", "Vadeli işlemler Premium ile kullanılabilir.\n\nHer işlemde kaldıracı, teminatı ve likidasyon fiyatını, borsadan gelen gerçekleşen PnL'i ve 30 günlük trader sıralamasını görürsün."},
        {"hl_rk_leverage", "Ortalama kaldıraç"},
        {"hl_rk_roi_account", "Mevduata göre ROI"},
        {"hl_rk_empty", "Henüz veri yok: sıralama için cüzdan başına 30 günde en az 5 kapanmış işlem gerekir."},
    };
    return t;
}

} // namespace

const char* trTr(const std::string& key) {
    const auto& t = tableTr();
    auto it = t.find(key);
    return it == t.end() ? nullptr : it->second;
}
